name: Cypress Tests

on: push

jobs:
  install:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress install
        uses: cypress-io/github-action@v6
        with:
          runTests: false
          build: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v4
        with:
          name: build
          if-no-files-found: error
          path: build

  cypress-run:
    runs-on: windows-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build

      - name: Install dependencies
        run: npm install
        
      - name: Cypress run
        run: npx cypress run
